# Google Cloud Run configuration
# Deploy with: gcloud run services replace app.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: registration-agent
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        # Cloud Run specific annotations
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/registration-agent:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SERVER_MODE
          value: "compliant"
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
